### ISSUE TITLE
Why does d3 handle the grading rather than the server?

### ISSUE THREAD

**Issue by stevemacn** [codementum/experimentr#58]
Should the grading be done on the server rather than in the d3, which is accessible by the participants? Potentially by reading the javascript I can tell whether I was positively or negatively 
primed. 

Maybe not a problem since most participants won't read the javascript

**Comment by codementum** [comment]
Thinking about this more-- it's really up to the module creator as to whether grading is done on the client or the server.

Right now most modules are client-side, so I expect grading will be done there.
